### ISSUE TITLE
'std::runtime_error' : Failed to create process lock

### ISSUE THREAD

**Issue by cave-git-p** [quartiq/picam#2]
I first would like to thank you for the nice module. I encounter the following error when I try to initialize the PICAM from a local user:

`terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create process lock (named: PrincetonInstruments::Pidi::FtdiUsb::CrossLock) (open-file): errno is 2
Aborted (core dumped)`

Of course if I run from root it works. Is there a work around for this?

Thank you again

**Comment by jordens** [comment]
I haven't seen that. Did you get the SDK with https://github.com/quartiq/picam/blob/master/get_sdk.sh? THere is some libftdi rewiring in there. And maybe just `strace` it to find out where it wants to create the lock. Picam is pretty badly coded when it comes to directory separators and adhering to any filesystem hierarchy standard. It wants to make lock files in bad places.

**Comment by cave-git-p** [comment]
Thanks for the prompt reply. It was my fault. I had PICAM installed before and run as root which saved some lock files I could not overwrite in /dev/shm/. After removing them now it works. Thanks again.
